### ISSUE TITLE
Library is incompatible with REST API version 10.0

### ISSUE THREAD

**Issue by andresonjdf** [PureStorage-OpenConnect/Monitoring#13]
Hello my friend @genegr !
[erro flashblade](https://user-images.githubusercontent.com/66372899/84192566-8f922480-aa70-11ea-98a7-d25c0b60cacf.PNG)

I followed your guidelines for adding flashblade storage monitoring, but when you run the script, the message "Library is incompatible with REST API version 10.0" is displayed. Could you help me solve this problem?

**Comment by genegr** [comment]
Hi @andresonjdf 
What version of PurityFB is your FlashBlade running on? Also it is important to know the version of the purity_fb python library. The latest version for the REST API is 1.9, but the libraries are backward compatible down to 1.0. With these two details I can try to reproduce the error in our lab.

**Comment by andresonjdf** [comment]
Hello @genegr 
 I apologize for the delay in answering you!
The version of PurityFB that is running on Flashblade is 2.4.3 and the python library purity_fb is 1.6.
Thank you in advance for your support.

**Comment by genegr** [comment]
Hi @andresonjdf 
That you are seeing is a known issue within PurityFB 2.4. Is not by any mean related to the python client and you can verify a directly related error is raised from the FB cli by the 'purealert list' command. That error is also the root cause of the failure for the analogous REST call executed by the exporter to retrieve the current open alerts. My suggestion is you engage with our Pure support to schedule an upgrade of the operating system to the latest version 3. Among the other improvements it will fix also this issue you are experiencing in the exporter.
